---
title: "Final Report"
output: html_notebook
---

```{r, include=FALSE}
library(furrr)
library(GEOquery) 
library(DT)
library(class)
library(tidyverse)
library(tuneR)
library(devtools)
library(ggplot2)
library(tsfeatures)
library(class)
library(cvTools)
library(randomForest)
library(GEOquery) 
library(R.utils)
library(reshape2)
library(limma)
library(dplyr)
library(e1071)
library(DT)
library(viridis)
library(plotly)
library(scales)
library(CPOP)
library(matrixStats)
library(visNetwork)
library(fairness)
library(caret)
library(ROCR)
set.seed(3887)
```

```{r}
# Data importing

# GSE21374 = getGEO("GSE21374")[[1]]
# GSE36059 = getGEO("GSE36059")[[1]]
# GSE48581 = getGEO("GSE48581")[[1]]

# GSE46474 = getGEO("GSE46474")[[1]]
# GSE129166 = getGEO("GSE129166")[[1]] 


# saveRDS(GSE21374, "data/GSE21374.rds") 
# saveRDS(GSE48581, "data/GSE48581.rds") 
# saveRDS(GSE36059, "data/GSE36059.rds")

# saveRDS(GSE46474, "data/GSE46474.rds")
# saveRDS(GSE129166, "data/GSE129166.rds")

# CPOP Model Building Datasets
GSE21374 = readRDS("data/GSE21374.rds")
GSE36059 <- readRDS("data/GSE36059.rds")
GSE48581 <- readRDS("data/GSE48581.rds")

# Auxilary Datasets
GSE46474 <- readRDS("data/GSE46474.rds") # Builds Biological Sex knn
user_input <- readRDS("data/GSE129166.rds") # External dataset used to generate final model, full GSE used here rather than an expression csv as was seen in the Shiny app to decrease pipeline complexity
```


# Executive Summary

# Background


# Methods
```{r}
# Transforms Affymetrics probe ID into Gene Name
gene_names = function(gse) {
  fData(gse)$`Gene Symbol` = unlist(lapply(strsplit(fData(gse)$`Gene Symbol`, " /// ", 1), `[`, 1))

  idx = which(!duplicated(fData(gse)$`Gene Symbol`) & !is.na(fData(gse)$`Gene Symbol`))
  gse = gse[idx,]
  rownames(gse) = fData(gse)$`Gene Symbol`
  
  return(gse)
}

GSE21374 = gene_names(GSE21374)
GSE36059 = gene_names(GSE36059)
GSE48581 = gene_names(GSE48581)
GSE46474 = gene_names(GSE46474)
user_input = gene_names(user_input)
```

```{r}
# Convert reject and stable labels to binary outcome vector (0,1)
p_GSE21374 = pData(GSE21374)
p_GSE48581 = pData(GSE48581) 
p_GSE36059 = pData(GSE36059)
p_ue = pData(user_input)
p_ue = p_ue %>% filter(characteristics_ch1 == "tissue: kidney allograft biopsy") # GSE129166 has a mix of blood and biopsy samples so we only extract the biopsy samples. In the shiny app, we assume that the input data is biopsy only
ue_biopsy_samp = rownames(p_ue)


p_GSE36059$diagnosis = ifelse(p_GSE36059$characteristics_ch1 == "diagnosis: non-rejecting", 0, 1)
p_GSE48581$diagnosis = ifelse(p_GSE48581$characteristics_ch1.1 == "diagnosis (tcmr, abmr, mixed, non-rejecting, nephrectomy): non-rejecting", 0, 1)
p_GSE21374$diagnosis = ifelse(p_GSE21374$characteristics_ch1.3 == "rejection/non rejection: nonrej", 0, 1)
userOutcomes = ifelse((p_ue$characteristics_ch1.1 == "tcmr (no: 0_borderline:1_TCMR:2): 0") & (p_ue$characteristics_ch1.2 == "abmr (no: 0_Yes:1): 0"), 0, 1)

y1 = as.factor(p_GSE36059$diagnosis)
y2 = as.factor(p_GSE48581$diagnosis)
y3 = as.factor(p_GSE21374$diagnosis)
userOutcomes = as.factor(userOutcomes)
```


```{r}
# Transforms and removes genes with low variance

exp_GSE36059 = (exprs(GSE36059)) # Import Expression data
Variance = rowVars(as.matrix(exp_GSE36059)) # Extract variance
Variance = as.data.frame(Variance) 
exp_GSE36059 = as.data.frame(exp_GSE36059)
exp_GSE36059 = cbind(exp_GSE36059, variance = Variance) # Add variance column to expression data
exp_GSE36059 = slice_max(exp_GSE36059, order_by = Variance, n = 300) # Orders expression data from most to least variable then takes the top 300 values
exp_GSE36059 = subset(exp_GSE36059, select = -c(Variance)) # removes the variance column
row_names_exp_GSE36059 = rownames(exp_GSE36059) # Takes the gene names for later


exp_GSE21374 = (exprs(GSE21374))
Variance = rowVars(as.matrix(exp_GSE21374))
Variance = as.data.frame(Variance)
exp_GSE21374 = as.data.frame(exp_GSE21374)
exp_GSE21374 = cbind(exp_GSE21374, variance = Variance)
exp_GSE21374 = slice_max(exp_GSE21374, order_by = Variance, n = 300)
exp_GSE21374 = subset(exp_GSE21374, select = -c(Variance))
row_names_exp_GSE21374 = rownames(exp_GSE21374)


exp_GSE48581 = (exprs(GSE48581))
Variance = rowVars(as.matrix(exp_GSE48581))
Variance = as.data.frame(Variance)
exp_GSE48581 = as.data.frame(exp_GSE48581)
exp_GSE48581 = cbind(exp_GSE48581, variance = Variance)
exp_GSE48581 = slice_max(exp_GSE48581, order_by = Variance, n = 300)
exp_GSE48581 = subset(exp_GSE48581, select = -c(Variance)) 
row_names_exp_GSE48581 = rownames(exp_GSE48581)


userExpression = exprs(user_input) 
Variance = rowVars(as.matrix(userExpression))
Variance = as.data.frame(Variance)
userExpression = as.data.frame(userExpression) %>% select(ue_biopsy_samp) # Only chooses biopsy samples
userExpression = cbind(userExpression, variance = Variance)
userExpression = slice_max(userExpression, order_by = Variance, n = 300)
userExpression = subset(userExpression, select = -c(Variance)) 
row_names_UE = rownames(userExpression)


```


```{r}
# Takes the common genes from the datasets
intersection = intersect(row_names_exp_GSE36059, row_names_exp_GSE21374)
intersection = intersect(intersection, row_names_exp_GSE48581)
intersection = intersect(intersection, row_names_UE)

exp_GSE36059 = as.data.frame(t(as.matrix(exp_GSE36059)))
exp_GSE36059 = subset(exp_GSE36059, select = c(intersection)) # select rows that contain the probe ids in intersection
      
exp_GSE21374 = as.data.frame(t(as.matrix(exp_GSE21374)))
exp_GSE21374 = subset(exp_GSE21374, select = c(intersection)) 

exp_GSE48581 = as.data.frame(t(as.matrix(exp_GSE48581)))
exp_GSE48581 = subset(exp_GSE48581, select = c(intersection)) 

userExpression = as.data.frame(t(as.matrix(userExpression)))
userExpression = subset(userExpression, select = c(intersection))
```


```{r}
z1 = exp_GSE36059 %>% as.matrix()
z2 = exp_GSE48581 %>% as.matrix()
z3 = exp_GSE21374 %>% as.matrix()
userExpression_z = userExpression %>% as.matrix()



# log transforms the data

exp_GSE36059_log <- exp_GSE36059
exp_GSE36059_log = exp_GSE36059_log + 1
exp_GSE36059_log = log(exp_GSE36059_log)

exp_GSE21374_log <- exp_GSE21374
exp_GSE21374_log = exp_GSE21374_log + 1
exp_GSE21374_log = log(exp_GSE21374_log)

exp_GSE48581_log <- exp_GSE48581
exp_GSE48581_log = exp_GSE48581_log + 1
exp_GSE48581_log = log(exp_GSE48581_log)

ue_log = userExpression
ue_log = ue_log + 1
ue_log = log(ue_log)


z1_log = exp_GSE36059_log  %>% as.matrix()
z3_log = exp_GSE21374_log %>% as.matrix()
z2_log = exp_GSE48581_log %>% as.matrix()
ue_log = ue_log %>% as.matrix()
```

```{r}
# Perform Pairwise difference calculation for later use
z1_pairwise = data.frame(pairwise_col_diff(z1_log) %>% as.matrix())
z2_pairwise = data.frame(pairwise_col_diff(z2_log) %>% as.matrix())
z3_pairwise = data.frame(pairwise_col_diff(z3_log) %>% as.matrix())
```


```{r, include=FALSE}
# Run cpop on each dataset combo 5 times and get the top features overall from each

cpop1 = data.frame("coef_name", "coef1", "coef2", "avg")

for (i in 1:5) {
  model = cpop_model(z1_log,
    ue_log,
    y1,
    userOutcomes, 
    w = NULL,
    n_features = 30,
    n_iter = 30,
    alpha = 1,
    family = "binomial",
    s = "lambda.min",
    cpop2_break = TRUE,
    cpop2_type = "sign",
    cpop2_mag = 1,
    cpop1_method = "normal",
    intercept = FALSE)
  cpop_coef = model$coef_tbl
  cpop_coef$avg = (abs(cpop_coef$coef1) + abs(cpop_coef$coef2)) / 2
  cpop1 = merge(cpop1, as.data.frame(cpop_coef), all = TRUE)
  
}

cpop1 = cpop1 %>% select(coef_name, coef1, coef2, avg) %>% filter(coef_name != "(Intercept)") %>% arrange(desc(avg))
cpop1 = subset(cpop1, !duplicated(subset(cpop1, select = c(coef_name))))
```

```{r, include=FALSE}
# Run cpop on each dataset combo 5 times and get the top features overall from each

cpop2 = data.frame("coef_name", "coef1", "coef2", "avg")

for (i in 1:5) {
  model = cpop_model(z2_log,
    ue_log,
    y2,
    userOutcomes, 
    w = NULL,
    n_features = 30,
    n_iter = 30,
    alpha = 1,
    family = "binomial",
    s = "lambda.min",
    cpop2_break = TRUE,
    cpop2_type = "sign",
    cpop2_mag = 1,
    cpop1_method = "normal",
    intercept = FALSE)
  cpop_coef = model$coef_tbl
  cpop_coef$avg = (abs(cpop_coef$coef1) + abs(cpop_coef$coef2)) / 2
  cpop2 = merge(cpop2, as.data.frame(cpop_coef), all = TRUE)
  
}

cpop2 = cpop2 %>% select(coef_name, coef1, coef2, avg) %>% filter(coef_name != "(Intercept)") %>% arrange(desc(avg))
cpop2 = subset(cpop2, !duplicated(subset(cpop2, select = c(coef_name))))
```

```{r, include=FALSE}
# Run cpop on each dataset combo 5 times and get the top features overall from each

cpop3 = data.frame("coef_name", "coef1", "coef2", "avg")

for (i in 1:5) {
  model = cpop_model(z3_log,
    ue_log,
    y3,
    userOutcomes, 
    w = NULL,
    n_features = 30,
    n_iter = 30,
    alpha = 1,
    family = "binomial",
    s = "lambda.min",
    cpop2_break = TRUE,
    cpop2_type = "sign",
    cpop2_mag = 1,
    cpop1_method = "normal",
    intercept = FALSE)
  cpop_coef = model$coef_tbl
  cpop_coef$avg = (abs(cpop_coef$coef1) + abs(cpop_coef$coef2)) / 2
  cpop3 = merge(cpop1, as.data.frame(cpop_coef), all = TRUE)
  
}

cpop3 = cpop3 %>% select(coef_name, coef1, coef2, avg) %>% filter(coef_name != "(Intercept)") %>% arrange(desc(avg))
cpop3 = subset(cpop3, !duplicated(subset(cpop3, select = c(coef_name))))
```

```{r}
# Merge the 3 CPOP model features together
rownames(cpop1) = cpop1$coef_name
rownames(cpop2) = cpop2$coef_name
rownames(cpop3) = cpop3$coef_name
results = merge(merge(cpop1, cpop2, all=FALSE, by = "coef_name"), cpop3, all=FALSE, by = "coef_name")
```

```{r}
row.names(results) = results$coef_name
results = results %>% select(-c(avg.x, avg.y, avg, coef_name))
results = abs(results)
results$average = rowMeans(results)
```




```{r}
# Quick function to simplify the pairwise difference taking. Was use predominantly to see what the different transformations did
pairwise = function(exp_GSE, transform_type) {
  z = exp_GSE
  if (transform_type == "Arc") {
    z = z / max(z)
    z = asin(sqrt(z))
    z = pairwise_col_diff(z) %>% as.matrix()
  }
  else if (transform_type == "Log") {
    z <- pairwise_col_diff(log(z +1))
    colnames(z) <- sub(".*\\.","",colnames(z))
    z = z %>% as.matrix()
  }
  else if (transform_type == "Pair"){
    z = z %>% as.matrix()
    z_pairwise = pairwise_col_diff(z) %>% as.matrix()
    
  }
  z = data.frame(z)
  
  return(z)
}
```





```{r}
# Generate visnetwork
coef <- rownames(results)
names = data.frame(feature1 = rep("",length(coef)),
                   feature2 = rep("",length(coef)),
                   coef_size = abs(results$average))

names$feature1 = sub("--.*", "", coef) #getting the first node from the coef-name vector of the results df
names$feature2 = sub(".*--", "", coef) #getting the second node from the coef-name vector of the results df

names_uniq = unique(c(names$feature1, names$feature2))
# names_uniq
numbers = names
#numbers
for (a in 1:nrow(numbers)) {
  for (i in 1:length(names_uniq)) {
    if (numbers$feature2[a] == names_uniq[i]) {
      numbers$feature2[a] = i
    }
  }
}
for (a in 1:nrow(numbers)) {
  for (i in 1:length(names_uniq)) {
    if (numbers$feature1[a] == names_uniq[i]) {
      numbers$feature1[a] = i
    }
  }
}
#numbers
clr = c()
for (a in 1:length(names_uniq)) {
  for (i in 1:nrow(names)) {
    if (names_uniq[a] == names[i,1] | names_uniq[a] == names[i,2]) {
      clr[a] = names$color[i]
    }
  }
}
#clr

cleanNames <- sub("--.*","",names_uniq)

edges = data.frame(from = numbers$feature1, to = numbers$feature2, value = names$coef_size)
nodes = data.frame(id = c(1:length(names_uniq)), 
                   label = names_uniq, 
                   # color = clr,
                   title = paste0('<a target="_blank" href = "https://www.genecards.org/cgi-bin/carddisp.pl?gene=',cleanNames,'">',cleanNames,'</a>'))
#nodes
  
visNetwork(nodes, edges, height = "500px", width = "100%", main = "Features Intersect Between CPOP Models")

```

```{r}
# Refresh the data for use in CV
ue <- as.data.frame(t(as.data.frame(exprs(user_input)) %>% select(ue_biopsy_samp))) 
temp_GSE36059 <- as.data.frame(t(exprs(GSE36059)))
temp_GSE48581 <- as.data.frame(t(exprs(GSE48581)))
temp_GSE21374 <- as.data.frame(t(exprs(GSE21374)))
```

```{r}
# Below function uses a KNN to predict biological sex for the incoming dataset
calculate_sex = function(dataframe) {
  colnames(dataframe) = tolower(colnames(dataframe))
  if ("xist" %in% colnames(dataframe) && "eif1ay" %in% colnames(dataframe) && "rps4y1" %in% colnames(dataframe)) {
    
    # Extracts the right genes from the input dataset
    outcome_df = dataframe %>% select("xist", "eif1ay", "rps4y1")
    outcome_df = pairwise(outcome_df, transform_type = "Log") %>% as.matrix()
    outcome_df = data.frame(outcome_df)
    
    # Performs cleaning on the training dataset GSE46474
    p_GSE46474 = pData(GSE46474)
    p_GSE46474$outcome = ifelse(p_GSE46474$characteristics_ch1.1 == "Sex: M", 0, 1) # Male is 0 and female is 1
    exprs_GSE46474 = data.frame(t(exprs(GSE46474)))
    colnames(exprs_GSE46474) = tolower(colnames(exprs_GSE46474))
    exprs_GSE46474 = exprs_GSE46474 %>% select("xist", "eif1ay", "rps4y1")
    exprs_GSE46474 = pairwise(exprs_GSE46474, transform_type="Log") 
    

    # Model generation. CV results are in the appendix
    model = knn(exprs_GSE46474, outcome_df, p_GSE46474$outcome, k = 3)
    
    return(model)
    
  }
  return(NULL)
}
```


```{r}
# Below code adds kidney graft outcome, biological sex info from KNNm and which dataset the observations are from

ue$outcome <- userOutcomes
ue$biological_sex <- calculate_sex(as.data.frame(userExpression))
ue$source <- c(rep("userUploadedData", length(rownames(userExpression))))

temp_GSE36059$outcome <- y1
temp_GSE36059$biological_sex <- calculate_sex(data.frame(t(exprs(GSE36059))))
temp_GSE36059$source <- c(rep("GSE36059", length(rownames(temp_GSE36059))))

temp_GSE48581$outcome <- y2
temp_GSE48581$biological_sex <- calculate_sex(data.frame(t(exprs(GSE48581))))
temp_GSE48581$source <- c(rep("GSE48581", length(rownames(temp_GSE48581))))

temp_GSE21374$outcome <- y3
temp_GSE21374$biological_sex <- calculate_sex(data.frame(t(exprs(GSE21374))))
temp_GSE21374$source <- c(rep("GSE21374", length(rownames(temp_GSE21374))))


# Combine the 4 datasets
combinedDataset <-  bind_rows(temp_GSE36059,temp_GSE48581, temp_GSE21374,ue )
outcome_source = combinedDataset %>% select(c(outcome, source, biological_sex)) # Temporarily remove non-gene cols in order to do variance analysis on each gene
combinedDataset = t(combinedDataset %>% select(-c(outcome, source, biological_sex)))

# Calculate variance of each gene
vars = rowVars(as.matrix(combinedDataset))
vars = as.data.frame(vars)

```



```{r}
# Take top 100 most variable genes 
combinedDataset = slice_max(cbind(combinedDataset, variance = vars), order_by = vars, n = 100)
combinedDataset = as.data.frame(t(subset(combinedDataset, select = -c(vars))))

combinedDatasetRaw = combinedDataset # For later boxplot

# Log transform the combined dataset
combinedDataset = combinedDataset + 1
combinedDataset = log(combinedDataset)
combinedDataset = cbind(combinedDataset, outcome_source)

combinedDatasetRaw$source = combinedDataset$source
```


```{r}
# CPOP Cross Validation on Combined Dataset

# split = cvTools::cvFolds(nrow(combinedDataset), 2)
# split = split$subsets[split$which == 1]
# 
# X1 = combinedDataset[split,] %>% select(-c(outcome, source, biological_sex))
# y1 = combinedDataset$outcome[split]
# 
# X2 = combinedDataset[-split, ] %>% select(-c(outcome, source, biological_sex))
# y2 = combinedDataset$outcome[-split]

X = combinedDataset %>% select(-c(outcome, source, biological_sex))
X = pairwise_col_diff(X)
y = combinedDataset$outcome
```


```{r, include=FALSE}
cvK = 5 # Number of CV folds
performance = vector(mode = "list", length = 5)

cvSets = cvTools::cvFolds(nrow(X), cvK)

cv_res = c()
cv_obsv = c()

for (j in 1:cvK) {
  test_id = cvSets$subsets[cvSets$which == j]

  X_train = X[-test_id, ] 
  X_test = X[test_id, ]
  
  y_train = y[-test_id]
  y_test = y[test_id]
  
  prediction = knn(X_train, X_test, y_train, k = 10)
  cv_res = append(cv_res, prediction)
  cv_obsv = append(cv_obsv, rownames(X_test))
  
}
iter_perf = data.frame(sample = cv_obsv, results = as.factor(cv_res))
performance[i] = iter_perf

  
  

```


```{r}
observation_df = data.frame(sample = cv_obsv, results = as.factor(cv_res))
rownames(observation_df) = observation_df$sample
observation_df = observation_df %>% select(results)
```

```{r}
performance_df = merge(combinedDataset, observation_df, by=0, all=TRUE) %>% select(Row.names, outcome, results, source, biological_sex)
count(performance_df$outcome == performance_df$results)/nrow(performance_df)
```
```{r}
performance_df$correct = ifelse(performance_df$results == performance_df$outcome, 1, 0)

gse21374 = performance_df %>% filter(source == "GSE21374")
gse36059 = performance_df %>% filter(source == "GSE36059")
gse48581 = performance_df %>% filter(source == "GSE48581")
user = performance_df %>% filter(source == "userUploadedData")

data_acc = c(count(gse21374$correct == 1)/nrow(gse21374), count(gse36059$correct == 1)/nrow(gse36059), count(gse48581$correct == 1)/nrow(gse48581), count(user$correct == 1)/nrow(user))
      data_pos = c(count(gse21374$results == 1)/nrow(gse21374), count(gse36059$results == 1)/nrow(gse36059), count(gse48581$results == 1)/nrow(gse48581), count(user$results == 1)/nrow(user))
data_obsv = c(nrow(gse21374), nrow(gse36059), nrow(gse48581), nrow(user))


male = performance_df %>% filter(biological_sex == 0)
female = performance_df %>% filter(biological_sex == 1)

gen_acc = c(count(male$correct == 1)/nrow(male), count(female$correct == 1)/nrow(female))
gen_pos = c(count(male$results == 1)/nrow(male), count(female$results == 1)/nrow(female))
gen_obsv = c(nrow(male), nrow(female))
```

```{r}
data.frame(`Dataset` = c("GSE21374", "GSE36059", "GSE48581", "User Input"), Observations = data_obsv, Accuracy = round(data_acc, 2), `Positive Prediction Rate` = round(data_pos, 2))

```
```{r}
data.frame(`Biological Sex` = c("Male", "Female"), Observations = gen_obsv, Accuracy = round(gen_acc, 2), `Positive Prediction Rate` = round(gen_pos, 2))
```



```{r}
total_perf = caret::confusionMatrix(as.factor(performance_df$results), as.factor(performance_df$outcome))

```


```{r}
combinedDatasetRaw = combinedDatasetRaw %>% select(-one_of("mean", "q1", "q3"))
combinedDatasetRaw$mean = rowMeans(combinedDatasetRaw %>% select(-c(source)))
combinedDatasetRaw$q1 = rowQuantiles(combinedDatasetRaw %>% select(-c(source, mean)) %>% as.matrix(), probs=c(0.25))
combinedDatasetRaw$q3 = rowQuantiles(combinedDatasetRaw %>% select(-c(source, mean, q1)) %>% as.matrix(), probs=c(0.75))
```

```{r}
ggplot(data = combinedDatasetRaw, aes(x = rownames(combinedDatasetRaw), y = mean)) +
        geom_point(aes(color = source), size = 0.1) +
        geom_errorbar(aes(ymin = q1,
                          ymax = q3,
                          color = source), size = 0.15,  alpha = 0.55) +
        
        theme(axis.ticks = element_blank()) +
        theme(axis.text.x = element_blank()) +
        xlab("Samples") +  ylab("Expression Level (Log)")+
        theme(axis.title.y=element_blank()) +
        labs(title = "Raw Data (Top 100 MOst Variable Genes)") +
        theme(plot.title = element_text(size=10)) + scale_color_viridis(discrete = TRUE, option = "inferno", alpha = 1, begin = 0, end = 0.8)
```
```{r}

combined_pairwise = combinedDataset %>% select(-c(outcome, source, biological_sex))
combined_pairwise = 1+combined_pairwise
combined_pairwise = log(combined_pairwise)

combined_pairwise = as.data.frame(pairwise_col_diff(combined_pairwise %>% as.matrix()))

combined_pairwise$source = combinedDataset$source
combined_pairwise$outcome = combinedDataset$outcome

```


```{r}

combined_pairwise$mean = rowMeans(combined_pairwise %>% select(-c(outcome, source)))
combined_pairwise$q1 = rowQuantiles(combined_pairwise %>% select(-c(outcome, source, mean)) %>% as.matrix(), probs=c(0.25))
combined_pairwise$q3 = rowQuantiles(combined_pairwise %>% select(-c(outcome, source, mean, q1)) %>% as.matrix(), probs=c(0.75))
```
```{r}
ggplot(data = combined_pairwise, aes(x = rownames(combined_pairwise), y = mean)) +
        geom_point(aes(color = source), size = 0.1) +
        geom_errorbar(aes(ymin = q1,
                          ymax = q3,
                          color = source), size = 0.15,  alpha = 0.55) +
        
        theme(axis.ticks = element_blank()) +
        theme(axis.text.x = element_blank()) +
        xlab("Samples") +  ylab("Expression Level (Log)")+
        theme(axis.title.y=element_blank()) +
        labs(title = "Log Transformed + Pairwise Difference") +
        theme(plot.title = element_text(size=10)) + scale_color_viridis(discrete = TRUE, option = "inferno", alpha = 1, begin = 0, end = 0.8)
```


# Results


# Discussion


# Conclusion



# Appendix


## Biological Sex Model


```{r}
p_GSE46474 = pData(GSE46474)
p_GSE46474$outcome = ifelse(p_GSE46474$characteristics_ch1.1 == "Sex: M", 0, 1) # Male is 0 and female is 1
exprs_GSE46474 = data.frame(t(exprs(GSE46474)))
exprs_GSE46474 = exprs_GSE46474 %>% select(c("XIST", "EIF1AY", "ANKRD44"))
exprs_GSE46474 = pairwise(exprs_GSE46474, transform_type="Log") %>% as.matrix()
exprs_GSE46474 = data.frame(exprs_GSE46474)
```

```{r}
X1 = exprs_GSE46474
y1 = p_GSE46474$outcome

cvK = 5 # Number of CV folds
cv_acc_knn = cv_50acc5_knn = c()

for (i in 1:50) {
  
  cvSets = cvTools::cvFolds(nrow(X1), cvK)
  
  for (j in 1:cvK) {
      test_id = cvSets$subsets[cvSets$which == j]
      X_test = X1[test_id, ]
      X_train = X1[-test_id, ]
      y_test = y1[test_id]
      y_train = y1[-test_id]
      #KNN
      fit <- knn(X_train, X_test, y_train, k = 3)
      cv_acc_knn[j] = mean(fit == y_test)
  }
  
  cv_50acc5_knn <- append(cv_50acc5_knn, mean(cv_acc_knn))
}
```




# Combined Feature Set VisNetwork
```{r}
combined_res = merge(merge(cpop1, cpop2, all=TRUE), cpop3, all=TRUE) %>% arrange(desc(avg))
combined_res = subset(combined_res, !duplicated(subset(combined_res, select = c(coef_name))))
```

```{r}
results = head(combined_res, 20)
coef <- results$coef_name
names = data.frame(feature1 = rep("",length(coef)),
                   feature2 = rep("",length(coef)),
                   coef_size = abs(results$avg))

names$feature1 = sub("--.*", "", coef) #getting the first node from the coef-name vector of the results df
names$feature2 = sub(".*--", "", coef) #getting the second node from the coef-name vector of the results df

names_uniq = unique(c(names$feature1, names$feature2))
# names_uniq
numbers = names
#numbers
for (a in 1:nrow(numbers)) {
  for (i in 1:length(names_uniq)) {
    if (numbers$feature2[a] == names_uniq[i]) {
      numbers$feature2[a] = i
    }
  }
}
for (a in 1:nrow(numbers)) {
  for (i in 1:length(names_uniq)) {
    if (numbers$feature1[a] == names_uniq[i]) {
      numbers$feature1[a] = i
    }
  }
}
#numbers
clr = c()
for (a in 1:length(names_uniq)) {
  for (i in 1:nrow(names)) {
    if (names_uniq[a] == names[i,1] | names_uniq[a] == names[i,2]) {
      clr[a] = names$color[i]
    }
  }
}
#clr

cleanNames <- sub("--.*","",names_uniq)

edges = data.frame(from = numbers$feature1, to = numbers$feature2, value = names$coef_size)
nodes = data.frame(id = c(1:length(names_uniq)), 
                   label = names_uniq, 
                   # color = clr,
                   title = paste0('<a target="_blank" href = "https://www.genecards.org/cgi-bin/carddisp.pl?gene=',cleanNames,'">',cleanNames,'</a>'))
#nodes
  
visNetwork(nodes, edges, height = "500px", width = "100%", main = "Top 20 Features by Coefficient Average From Complete CPOP Models Set")
```

